### ISSUE TITLE
Chrome extension / Vue.js: Make the localstorage work

### ISSUE THREAD

**Issue by danilowoz** [danilowoz/Vuesualizen#5]
The plugin is working on the web and localhost, however the package that I'm using to control the storage has some problem to work inside the chrome extension. 

I am not sure of the problem because I don't have enough skill to work on it, but I think if you've worked with chrome extension it would be very easy!

You can see the build at `/build` with `manifest.json`.

**Comment by douglasgimli** [comment]
@danilowoz I'm almost sure that the problem is that localStorage it's not direct accessible by the Chrome Extension APIs. (https://stackoverflow.com/questions/3937000/chrome-extension-accessing-localstorage-in-content-script)

I can try this one, creating a custom small lib to store the data using Chrome Extension Local Storage, what you think?

**Comment by danilowoz** [comment]
I could kiss you if you solve this problem hahahah
Sure, I think that have some alternatives, but it didn't work for me, so feel free to try and tell me the results that you get

**Comment by mubaidr** [comment]
The package you are using manages local storage within context for the page on which extension is currently running. I believe you need to store global data  in your extension for which purpose there are two options, as mentioned in the link above:
- Use chrome Storage api 👍 
- Use message api to send data to background script, which in turn saves data. 👎

**Comment by danilowoz** [comment]
I finally got to solve in the #8. 
First I removed the sandbox in the `manifest.json` and I don't why my app didn't have the `render` on the Vue initialization.

Thanks for helping me. 🎉
